// All user-facing text. Spanish is the default; English is the toggle.
export type Lang = "es" | "en";

export const strings = {
  es: {
    appTitle: "Tarjeta de Tiempo",
    foreman: "Mayordomo",
    pickForeman: "¿Quién eres?",
    changeForeman: "Cambiar",
    date: "Fecha",
    job: "Trabajo / Obra",
    jobPlaceholder: "Nombre del trabajo",
    crew: "Cuadrilla",
    addWorkerSearch: "Buscar o agregar trabajador",
    searchForeman: "Buscar mayordomo",
    addNew: "Agregar",
    hours: "Horas",
    applyAll: "Horas para todos",
    applyAllTitle: "Horas para todo el equipo",
    crewLabel: "Equipo",
    workDone: "Trabajo realizado",
    workDonePlaceholder: "Qué se hizo",
    notes: "Notas",
    notesPlaceholder: "Lluvia, salió temprano, inspector en sitio…",
    review: "Revisar",
    back: "Regresar",
    submit: "Enviar",
    submitting: "Enviando…",
    sent: "Enviado ✓",
    total: "Total de horas",
    clear: "Borrar",
    clearConfirm: "¿Borrar todo el formulario?",
    selfRemoveConfirm: "Te estás quitando de la cuadrilla. ¿Continuar?",
    yes: "Sí",
    no: "No",
    logAnother: "Registrar otro trabajo de hoy",
    logAnotherCard: "Registrar otra tarjeta",
    newTimecard: "Nueva tarjeta",
    failTitle: "No se pudo enviar",
    failBody: "Revisa tu señal e inténtalo de nuevo. Tu información sigue aquí.",
    tryAgain: "Intentar de nuevo",
    noCrew: "Agrega al menos un trabajador.",
    noJob: "Escribe el nombre del trabajo.",
    noForeman: "Selecciona quién eres primero.",
    noHours: "Cada trabajador necesita horas.",
    reviewTitle: "Revisa antes de enviar",
    workerHeader: "Trabajador",
    workersCount: "Trabajadores",
    hoursHeader: "Horas",
    addAnother: "Agregar otro",
    done: "Listo",
    selectForemanFirst: "Primero, ¿quién eres?",
    continue: "Continuar",
    remove: "Quitar",
    loading: "Cargando…",
    updated: "✓ Actualizado",
    refresh: "Actualizar lista",
    dateNotToday: "Esta tarjeta es del {date}. Confirma que la fecha es correcta.",
    noFutureDate: "No se puede enviar una tarjeta con fecha futura.",
    reportsTitle: "Reportes",
    enterPin: "Ingresa el PIN",
    wrongPin: "PIN incorrecto",
    weekLabel: "Semana",
    includeFlags: "Incluir alertas",
    generateSend: "Generar y enviar",
    generating: "Generando…",
    reportSent: "✓ Reporte enviado",
    reportFail: "No se pudo generar el reporte. Inténtalo de nuevo.",
    close: "Cerrar",
    customRange: "Rango personalizado…",
    fromLabel: "Desde",
    toLabel: "Hasta",
    foremanLabel: "Mayordomo",
    allForemen: "Todos",
    reportLanguage: "Idioma del reporte",
    generateView: "Generar y ver",
    reportTypeLabel: "Tipo de reporte",
    reportTypeJob: "Semanal (por obra)",
    reportTypeWorker: "Semanal (por trabajador)",
    reportTypeForeman: "Reporte de mayordomo",
  },
  en: {
    appTitle: "Timecard",
    foreman: "Foreman",
    pickForeman: "Who are you?",
    changeForeman: "Change",
    date: "Date",
    job: "Job",
    jobPlaceholder: "Job name",
    crew: "Crew",
    addWorkerSearch: "Search or add worker",
    searchForeman: "Search foreman",
    addNew: "Add",
    hours: "Hours",
    applyAll: "Set all hours",
    applyAllTitle: "Set hours for everyone",
    crewLabel: "Crew",
    workDone: "Work done",
    workDonePlaceholder: "What was done",
    notes: "Notes",
    notesPlaceholder: "Rain, left early, inspector on site…",
    review: "Review",
    back: "Back",
    submit: "Send",
    submitting: "Sending…",
    sent: "Sent ✓",
    total: "Total hours",
    clear: "Clear",
    clearConfirm: "Clear the whole form?",
    selfRemoveConfirm: "You're removing yourself from the crew. Continue?",
    yes: "Yes",
    no: "No",
    logAnother: "Log another job for today",
    logAnotherCard: "Log another timecard",
    newTimecard: "New timecard",
    failTitle: "Couldn't send",
    failBody: "Check your signal and try again. Your info is still here.",
    tryAgain: "Try again",
    noCrew: "Add at least one worker.",
    noJob: "Enter the job name.",
    noForeman: "Pick who you are first.",
    noHours: "Every worker needs hours.",
    reviewTitle: "Review before sending",
    workerHeader: "Worker",
    workersCount: "Workers",
    hoursHeader: "Hours",
    addAnother: "Add another",
    done: "Done",
    selectForemanFirst: "First, who are you?",
    continue: "Continue",
    remove: "Remove",
    loading: "Loading…",
    updated: "✓ Updated",
    refresh: "Refresh list",
    dateNotToday: "This timecard is dated {date}. Please confirm the date is correct.",
    noFutureDate: "Can't submit a timecard for a future date.",
    reportsTitle: "Reports",
    enterPin: "Enter PIN",
    wrongPin: "Wrong PIN",
    weekLabel: "Week",
    includeFlags: "Include flags",
    generateSend: "Generate & send",
    generating: "Generating…",
    reportSent: "✓ Report sent",
    reportFail: "Couldn't generate the report. Try again.",
    close: "Close",
    customRange: "Custom range…",
    fromLabel: "From",
    toLabel: "To",
    foremanLabel: "Foreman",
    allForemen: "All foremen",
    reportLanguage: "Report language",
    generateView: "Generate & view",
    reportTypeLabel: "Report type",
    reportTypeJob: "Weekly (by job)",
    reportTypeWorker: "Weekly (by worker)",
    reportTypeForeman: "Foreman report",
  },
} as const;

export function t(lang: Lang) {
  return strings[lang];
}
