// All user-facing text. Spanish is the default; English is the toggle.
export type Lang = "es" | "en";

export const strings = {
  es: {
    appTitle: "Tarjeta de Tiempo",
    foreman: "Mayordomo",
    pickForeman: "¿Quién eres?",
    changeForeman: "Cambiar",
    date: "Fecha",
    job: "Trabajo / Obra",
    jobPlaceholder: "Nombre del trabajo",
    crew: "Cuadrilla",
    addWorkerSearch: "Buscar o agregar trabajador",
    addNew: "Agregar",
    hours: "Horas",
    applyAll: "Aplicar a todos",
    workDone: "Trabajo realizado",
    workDonePlaceholder: "Qué se hizo",
    notes: "Notas",
    notesPlaceholder: "Lluvia, salió temprano, inspector en sitio…",
    review: "Revisar",
    back: "Regresar",
    submit: "Enviar",
    submitting: "Enviando…",
    sent: "Enviado ✓",
    total: "Total de horas",
    clear: "Borrar",
    clearConfirm: "¿Borrar todo el formulario?",
    yes: "Sí",
    no: "No",
    logAnother: "Registrar otro trabajo de hoy",
    newTimecard: "Nueva tarjeta",
    failTitle: "No se pudo enviar",
    failBody: "Revisa tu señal e inténtalo de nuevo. Tu información sigue aquí.",
    tryAgain: "Intentar de nuevo",
    noCrew: "Agrega al menos un trabajador.",
    noJob: "Escribe el nombre del trabajo.",
    noForeman: "Selecciona quién eres primero.",
    noHours: "Cada trabajador necesita horas.",
    reviewTitle: "Revisa antes de enviar",
    workerHeader: "Trabajador",
    hoursHeader: "Horas",
    addAnother: "Agregar otro",
    done: "Listo",
    selectForemanFirst: "Primero, ¿quién eres?",
    continue: "Continuar",
    remove: "Quitar",
    loading: "Cargando…",
  },
  en: {
    appTitle: "Timecard",
    foreman: "Foreman",
    pickForeman: "Who are you?",
    changeForeman: "Change",
    date: "Date",
    job: "Job",
    jobPlaceholder: "Job name",
    crew: "Crew",
    addWorkerSearch: "Search or add worker",
    addNew: "Add",
    hours: "Hours",
    applyAll: "Apply to all",
    workDone: "Work done",
    workDonePlaceholder: "What was done",
    notes: "Notes",
    notesPlaceholder: "Rain, left early, inspector on site…",
    review: "Review",
    back: "Back",
    submit: "Send",
    submitting: "Sending…",
    sent: "Sent ✓",
    total: "Total hours",
    clear: "Clear",
    clearConfirm: "Clear the whole form?",
    yes: "Yes",
    no: "No",
    logAnother: "Log another job for today",
    newTimecard: "New timecard",
    failTitle: "Couldn't send",
    failBody: "Check your signal and try again. Your info is still here.",
    tryAgain: "Try again",
    noCrew: "Add at least one worker.",
    noJob: "Enter the job name.",
    noForeman: "Pick who you are first.",
    noHours: "Every worker needs hours.",
    reviewTitle: "Review before sending",
    workerHeader: "Worker",
    hoursHeader: "Hours",
    addAnother: "Add another",
    done: "Done",
    selectForemanFirst: "First, who are you?",
    continue: "Continue",
    remove: "Remove",
    loading: "Loading…",
  },
} as const;

export function t(lang: Lang) {
  return strings[lang];
}
